# Alpine Linux with OpenJDK JRE
#FROM openjdk:8-jre-alpine
# copy WAR into image
#COPY aws-web-0.0.1-SNAPSHOT.war /app.war 
# run application with this command line 
#CMD ["/usr/bin/java", "-jar", "-Dspring.profiles.active=default", "/app.war"]

From tomcat:8.0.51-jre8-alpine
CMD ["catalina.sh","run"]
